config/routes.rb
ShareYourStory::Application.routes.draw do
  get "essays/new"

  get "sessions/new"

   resources :users
   resources :sessions,   :only => [:new, :create, :destroy]
   resources :microposts, :only => [:create, :destroy]
  
   resources :essays do
     resources :rankings
   end
  

    get "users/new"

    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/control', :to => 'pages#control'
    match '/bio', :to => 'pages#bio'
    match '/scoreindex0', :to => 'essays#scoreindex0'
    match '/scoreindex1', :to => 'essays#scoreindex1'
    match '/scoreindex2', :to => 'essays#scoreindex2'
    match '/scoreindex3', :to => 'essays#scoreindex3'
    match '/scoreindex4', :to => 'essays#scoreindex4'
    match '/scoreindex5', :to => 'essays#scoreindex5'
    match '/scoreindex6', :to => 'essays#scoreindex6'
    match '/scoreindex7', :to => 'essays#scoreindex7'
    match '/scoreindex8', :to => 'essays#scoreindex8'
    match '/scoreindex9', :to => 'essays#scoreindex9'
    match '/scoreindex10', :to => 'essays#scoreindex10'
    root :to => 'pages#home'
    
    
    

end

app/views/pages/about.html.erb
		<h1>Come Back Soon!</h1>
		<p>
			We are currently under construction.
		</p>

app/views/pages/bio.html.erb
<h1>Come Back Soon!</h1>
<p>
	We are currently under construction.
</p>

app/views/pages/contact.html.erb
<h1>Come Back Soon!</h1>
<p>
	We are currently under construction.
</p>

app/views/pages/control.html.erb
<% if signed_in? && current_user.admin?%>
<h1><center>THE CONTROL CENTER</center></h1>

<h2>Stats</h2>
<p>
<strong>Total Users: </strong><%= User.count %> <br>
<strong>Total Essays: </strong><%= Essay.count %> <br>
<strong>Total Rankings: </strong><%= Ranking.count %> <br>
<strong>Mean Rankings Per User</strong> <%= @mean_rank_per_user%> <br>
<strong>Mean Score: </strong> <%= @mean_score %>
</p>

<h2>Top Essays<h2>
	<table>
	
	<tr>
	<th>Position</th>
	<th>Essay</th>
	<th>Score</th>
	</tr>
	
	<%@essays_arr.each do |i|%>
	<tr class="users center">
	<td><%= @essays_arr.index(i)+1%></td>
	<td><%= render Essay.find(i[0])%></td>
	<td><%= i[1]%></td>
	</tr>
	<%end%>
	</table>

<% else %>
  <%= link_to "Please sign in!", signin_path %>
<% end %>

app/views/pages/help.html.erb
<h1>Come Back Soon!</h1>
<p>
	We are currently under construction.
</p>

app/views/pages/home.html.erb
<% if signed_in? %>
  

<% if !@unranked.empty?%>
<h1>
	<center>
	Some Essays You Haven't Ranked
	</cetner>
</h1>
<%= render 'shared/essay_list' %>
<%else%>
<br>
<h2><center>You've ranked all the essays!<center></h2>
<%end%>

<% else %>

  <h1 class="welcome">Share Your Story!</h1>

  <p class="indent">
    This is the website used internally for the <em>Share Your Story Scholarship and Book Project</em>. <em>Share Your Story</em> is a non-profit designed to
	help low income students pay for college both by providing fiscal assistance and by educating the public through a compilation of college essays.
  </p>
  <p class="indent">
		If you are interested in the project or would like to apply for the scholarship, please see our public website, <a href="http://www.ShareYourStoryEssays.com">ShareYourStoryEssays.com</a>.
  </p>
  <p class="indent">
	If you are here because you were selected as a reader, please sign up now!
  <p>

  <%= link_to "Register now!", signup_path, :class => "signup_button round border" %>

<% end %>