config/routes.rb
ShareYourStory::Application.routes.draw do
  get "essays/new"

  get "sessions/new"

   resources :users
   resources :sessions,   :only => [:new, :create, :destroy]
   resources :microposts, :only => [:create, :destroy]
  
   resources :essays do
     resources :rankings
   end
  

    get "users/new"

    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'
    match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/help',    :to => 'pages#help'
    match '/control', :to => 'pages#control'
    match '/bio', :to => 'pages#bio'
    match '/scoreindex0', :to => 'essays#scoreindex0'
    match '/scoreindex1', :to => 'essays#scoreindex1'
    match '/scoreindex2', :to => 'essays#scoreindex2'
    match '/scoreindex3', :to => 'essays#scoreindex3'
    match '/scoreindex4', :to => 'essays#scoreindex4'
    match '/scoreindex5', :to => 'essays#scoreindex5'
    match '/scoreindex6', :to => 'essays#scoreindex6'
    match '/scoreindex7', :to => 'essays#scoreindex7'
    match '/scoreindex8', :to => 'essays#scoreindex8'
    match '/scoreindex9', :to => 'essays#scoreindex9'
    match '/scoreindex10', :to => 'essays#scoreindex10'
    root :to => 'pages#home'
    
    
    

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round border shadow">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "The Bios", bio_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	
  <strong>
	<%link_to logo, root_path %>
	<div class="logo">
	<%= link_to "Share Your Story", root_path, {:style=>'color:#FFFFFF;text-decoration:none;', :class => "css_class"} %>
	</div>
  </strong>
  <nav class="round border shadow topnav">
	
    <ul>
	
	  <% if signed_in? && current_user.admin? %>
	  <li><%= link_to "CONTROL CENTER", control_path %>
	  <%end%>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Readers", users_path %></li>
	  <li><%= link_to "Essays", essays_path %></li>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	  <li><%= link_to "Help", help_path %></li>
      <% end %>
      
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>

</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=title%></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :defaults %>
  </head>
  <body>
	
    	<div class="container">
	
      	<%= render 'layouts/header' %>
     
	      	<section class="round border shadow pad">
	        	<% flash.each do |key, value| %>
	          	<div class="flash <%= key %>"><%= value %></div>
	        	<% end %>
	        	<%= yield %>
	      	</section>
   			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
    	</div>
		
	
  </body>
</html>